### ISSUE TITLE
Fails to install using Cabal

### ISSUE THREAD

**Issue by DemiMarie** [TomMD/crypto-api#26] opened 2017-02-12 20:39 UTC
This package fails to install using Cabal.  The error is

```
Resolving dependencies...
Configuring crypto-api-0.13.2...
Building crypto-api-0.13.2...
Failed to install crypto-api-0.13.2
Build log ( /home/dobenour/.cabal/logs/ghc-8.0.2/crypto-api-0.13.2-IWY9ufi9eli620ZIpN2T4R.log ):
cabal: Entering directory '/tmp/cabal-tmp-10176/crypto-api-0.13.2'
Configuring crypto-api-0.13.2...
Preprocessing library crypto-api-0.13.2...
[ 1 of 11] Compiling Crypto.Util      ( Crypto/Util.hs, dist/build/Crypto/Util.o )
[ 2 of 11] Compiling Crypto.Types     ( Crypto/Types.hs, dist/build/Crypto/Types.o )
[ 3 of 11] Compiling Crypto.Random    ( Crypto/Random.hs, dist/build/Crypto/Random.o )
[ 4 of 11] Compiling Crypto.Classes[boot] ( Crypto/Classes.hs-boot, dist/build/Crypto/Classes.o-boot )
[ 5 of 11] Compiling Crypto.Modes[boot] ( Crypto/Modes.hs-boot, dist/build/Crypto/Modes.o-boot )
[ 6 of 11] Compiling Crypto.Classes   ( Crypto/Classes.hs, dist/build/Crypto/Classes.o )
[ 7 of 11] Compiling Crypto.Classes.Exceptions ( Crypto/Classes/Exceptions.hs, dist/build/Crypto/Classes/Exceptions.o )
[ 8 of 11] Compiling Crypto.HMAC      ( Crypto/HMAC.hs, dist/build/Crypto/HMAC.o )
[ 9 of 11] Compiling Crypto.Padding   ( Crypto/Padding.hs, dist/build/Crypto/Padding.o )
[10 of 11] Compiling Crypto.CPoly     ( Crypto/CPoly.hs, dist/build/Crypto/CPoly.o )
[11 of 11] Compiling Crypto.Modes     ( Crypto/Modes.hs, dist/build/Crypto/Modes.o )
[ 1 of 11] Compiling Crypto.Util      ( Crypto/Util.hs, dist/build/Crypto/Util.p_o )
[ 2 of 11] Compiling Crypto.Types     ( Crypto/Types.hs, dist/build/Crypto/Types.p_o )
[ 3 of 11] Compiling Crypto.Random    ( Crypto/Random.hs, dist/build/Crypto/Random.p_o )
[ 4 of 11] Compiling Crypto.Classes[boot] ( Crypto/Classes.hs-boot, dist/build/Crypto/Classes.p_o-boot )
[ 5 of 11] Compiling Crypto.Modes[boot] ( Crypto/Modes.hs-boot, dist/build/Crypto/Modes.p_o-boot )
[ 6 of 11] Compiling Crypto.Classes   ( Crypto/Classes.hs, dist/build/Crypto/Classes.p_o )
[ 7 of 11] Compiling Crypto.Classes.Exceptions ( Crypto/Classes/Exceptions.hs, dist/build/Crypto/Classes/Exceptions.p_o )
[ 8 of 11] Compiling Crypto.HMAC      ( Crypto/HMAC.hs, dist/build/Crypto/HMAC.p_o )
[ 9 of 11] Compiling Crypto.Padding   ( Crypto/Padding.hs, dist/build/Crypto/Padding.p_o )
[10 of 11] Compiling Crypto.CPoly     ( Crypto/CPoly.hs, dist/build/Crypto/CPoly.p_o )
[11 of 11] Compiling Crypto.Modes     ( Crypto/Modes.hs, dist/build/Crypto/Modes.p_o )
/usr/bin/ld: cannot find -lHSentropy-0.3.7-C9ixbQgjWSQ6qUZQMdhcjS-ghc8.0.2
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
cabal: Leaving directory '/tmp/cabal-tmp-10176/crypto-api-0.13.2'
cabal: Error: some packages failed to install:
crypto-api-0.13.2-IWY9ufi9eli620ZIpN2T4R failed during the building phase. The
exception was:
ExitFailure 1
```

**Comment by ntc2** [comment] 2017-03-22 01:22
I also have this same problem about `ld` not finding `-lHSentropy-0.3.7-*-ghc8.0.2` using `cabal new-build` and GHC 8.0.2 to install `crypto-api-0.13.2` as a dependency. However, I'm able to `cabal new-build` successfully using GHC 8.0.1. Stack is able to build `crypto-api-0.13.2` against both GHC 8.0.2 and 8.0.1, using `entropy-0.3.7` in both cases.

No idea how to trouble shoot this for GHC 8.0.2 and Cabal.

**Comment by TomMD** [comment] 2017-03-22 16:56
What platform are you fellows using?

I've confirmed crypto-api 0.13.2 installs on my OS-X system with GHC 8.0.1 and a fresh sandbox.

With GHC 8.0.2 it also succeeds but I noticed:

```
/var/folders/0x/hlxcgy9n5714ryp0gkn5hkmm0000gp/T/pkgConf-entropy-0.3823378840143542612.7:
Unrecognized field dynamic-library-dirs on line 26
```

**Comment by TomMD** [comment] 2017-03-22 17:01
On Linux x64 using GHC 8.0.2 I also had no issues.  This was with Cabal 1.24.2.0 (cabal install 1.24.0.2).  The OS-X system was running Cabal 1.24.0.0.

**Comment by TomMD** [comment] 2017-03-22 17:03
So at this point I can't debug the problem because I can't reproduce it.  If you, @ntc2, can give me access to a machine then I'll poke around a little.  If either of you can pin the problem down to a particular configuration, or even get the problem to disappear by updating any tooling, then that would go a long way towards identifying the issue or deciding it isn't worthy of further investigation.

**Comment by ntc2** [comment] 2017-03-22 17:45
I'm on Linux x64 (Ubuntu 16.04). My Cabal versions are 1.24.0.0 for both the library and `cabal-install`. I also get that warning about `dynamic-lib-dirs` with 8.0.2+Cabal. I don't know what that flag is supposed to do, but I see that the directory structure for the *dynamic* libs/`.so` files is different between GHC 8.0.1 and 8.0.2 with Cabal:
```
 find ~/.cabal/ -name '*HSentropy*'      
/home/conathan/.cabal/store/ghc-8.0.2/entropy-0.3.7-289b2be235f237a3918a18b49c92c31f8990b9ed13fbba30e08e2c91b42be837/lib/x86_64-linux-ghc-8.0.2/libHSentropy-0.3.7-289b2be235f237a3918a18b49c92c31f8990b9ed13fbba30e08e2c91b42be837-ghc8.0.2.so
/home/conathan/.cabal/store/ghc-8.0.2/entropy-0.3.7-289b2be235f237a3918a18b49c92c31f8990b9ed13fbba30e08e2c91b42be837/lib/libHSentropy-0.3.7-289b2be235f237a3918a18b49c92c31f8990b9ed13fbba30e08e2c91b42be837.a
/home/conathan/.cabal/store/ghc-8.0.1/entropy-0.3.7-b4a8fcb8557aadddb472eba6f9c58e852a1baf43aab3fc07f02a99d16d61c9cf/lib/libHSentropy-0.3.7-b4a8fcb8557aadddb472eba6f9c58e852a1baf43aab3fc07f02a99d16d61c9cf.a
/home/conathan/.cabal/store/ghc-8.0.1/entropy-0.3.7-b4a8fcb8557aadddb472eba6f9c58e852a1baf43aab3fc07f02a99d16d61c9cf/lib/libHSentropy-0.3.7-b4a8fcb8557aadddb472eba6f9c58e852a1baf43aab3fc07f02a99d16d61c9cf-ghc8.0.1.so
```
I'm going to try upgrading my Cabal library and installer and see if that helps.

**Comment by ntc2** [comment] 2017-03-22 18:11
Upgrading to Cabal 1.24.2.0 and `cabal-install` 1.24.0.2 solved the problem, so I think you can close this. Thanks!

**Comment by TomMD** [comment] 2017-03-22 20:23
Thanks for confirming @ntc2

**Closed by TomMD** 2017-03-22 20:23 UTC
